Controllers films users
heydancer/java-filmorate pull request #1
Opened 2022-10-28 14:25 UTC by heydancer

2022-10-29 10:07 UTC, ErkinKasymaliev requested changes
Александр, здравтвуйте!
Отличная работа, но есть где можно доработать

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +@RequestMapping("/films")
отлично

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/GlobalService.java
> +public interface GlobalService<T> {
ничего себе, очень хорошо!

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Service
отлично, вы уже сами изучили @Service и сервисный слой

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    @NotNull(message = "Name cannot be null")
все отлично!

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private static final String EMAIL_PATTERN = "^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@" +
огонь!

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/GlobalService.java
> +public interface GlobalService<T> {
а что если сделаете не интерфейсом, а абстрактным классом.

public abstract class AbstractService<T> {
       public T create(final T data) {
		тут реализовано одинаково для Film и User
	}

	public T update(final T data) {
		тут реализовано одинаково для Film и User
	}

	public List<T> getAll() {
		тут реализовано одинаково для Film и User
	}

	abstract void validate(T data); -- а этот надо переоперделить, так как валидация для Film и User разные. И валидаторы из контроллеров можно убрать

2022-10-29 10:07 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private void filmValidationCheck(Film film) {
раз уж вы сделали сервисы, то лучше валидаторы тоже туда убрать из контроллеров

2022-11-01 14:38 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/service/GlobalService.java
> +public interface GlobalService<T> {
Поправил

2022-11-02 14:11 UTC, ErkinKasymaliev requested changes
Александр, отлично!
Насчет тестов - нужны тесты на валидаторы

2022-11-02 14:11 UTC, ErkinKasymaliev commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
я уточнил насчет тестов, вы должны написать тесты на валидаторы

2022-11-02 14:11 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/GlobalService.java
> +public abstract class GlobalService<T> {
огонь!

2022-11-04 10:26 UTC, heydancer commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +	@Test
добавил

2022-11-04 10:45 UTC, ErkinKasymaliev approved these changes
отлично! работа принята

2022-11-14 09:38 UTC, merged