Add database
heydancer/java-filmorate pull request #6
Opened 2022-12-15 18:31 UTC by heydancer

2022-12-17 09:53 UTC, ErkinKasymaliev requested changes
Привет, оставил комменты

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmSqlQueries.java
> +    static final String ADD_FILM = "INSERT INTO films(name,description, release_date, duration, mpa_id) " +
а это вы здорово придумали)

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmStorage filmStorage;
1) нельзя было удалять InMemoryFilmStorage. 
2) а здесь инжектить, используя @Qualifier - который позволяет инжектить определенную имплементацию
3) также можете почить про @Primary

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final UserStorage userStorage;
1) нельзя было удалять InMemoryUserStorage. 
2) а здесь инжектить, используя @Qualifier - который позволяет инжектить определенную имплементацию
3) также можете почить про @Primary

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return getData(filmId);
давайте здесь просто film возвращать, не надо делать лишний запрос в БД

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return getData(filmId);
давайте здесь просто film возвращать, не надо делать лишний запрос в БД

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        jdbcTemplate.update(FilmSqlQueries.REMOVE_FILM, filmId);
здесь .update() вернет число обновленных/удаленных строк. Если вернет 0, значит такой filmId не найден. Отсюда вот эта проверка Film removedFilm = getData(filmId); будет лишней.

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        jdbcTemplate.update(UserSqlQueries.UPDATE_USER, user.getName(), user.getEmail(),
здесь .update() вернет число обновленных/удаленных строк. Если вернет 0, значит такой userId не найден. Отсюда вот эта проверка Film removedFilm = getData(filmId); будет лишней.

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getData(userId);
давайте просят user возвращать

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getData(userId);
давайте просят user возвращать

2022-12-17 09:53 UTC, ErkinKasymaliev commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -public class FilmService extends GlobalService<Film> {
жалко что удалили GlobalService<>

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getData(userId);
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        return getData(userId);
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java
> +        jdbcTemplate.update(UserSqlQueries.UPDATE_USER, user.getName(), user.getEmail(),
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        jdbcTemplate.update(FilmSqlQueries.REMOVE_FILM, filmId);
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return getData(filmId);
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return getData(filmId);
поправил

2022-12-17 21:35 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +    private final UserStorage userStorage;
Готово

2022-12-17 21:36 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +    private final FilmStorage filmStorage;
Готово!

2022-12-17 21:37 UTC, heydancer commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> -public class FilmService extends GlobalService<Film> {
Куча проблем вылезло когда я пытался объединить с бд. В свободное время попробую подружить, всю голову уже сломал

2022-12-18 09:34 UTC, ErkinKasymaliev approved these changes
привет, отлично, все замечания исправлены. Работа принята

2022-12-19 12:38 UTC, merged